[package]
name = "alias_buddy"
version = "0.1.0"
authors = ["Static Codes <210101922+Static-Codes@users.noreply.github.com>" ]
license = "Unlicense"
edition = "2024"

[dependencies]
regex = "1.12.2"
dialoguer = "0.12.0"