[package]
name = "alias_buddy"
version = "0.1.0"
authors = ["Static Codes <210101922+Static-Codes@users.noreply.github.com>" ]
license = "Unlicense"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"